### ISSUE TITLE
tutorial section: Parsing a subset of a GCTX file

### ISSUE THREAD

**Issue by antonkratz** [cmap/cmapR#10]
In the tutorial, section "Parsing a subset of a GCTX file":
`sig_ids <- col_meta$sig_id[idx]`
This will not work because two lines earlier the metadata file has been loaded with `row.names=1`. So, there is no column `sig_id` anymore! Therefore `sig_ids` will be NULL (empty).

One solution would be to replace
`sig_ids <- col_meta$sig_id[idx]`
with
`sig_ids <- row.names(col_meta[idx,])`.

`sig_ids` is now a list of rownames.

**Comment by tnat1031** [comment]
thanks @antonkratz ! just pushed a fix
