### ISSUE TITLE
how to retrieve the connectivity score (tau) for any given combination?

### ISSUE THREAD

**Issue by antonkratz** [cmap/cmapR#12]
I know that for a given L1000 perturbagen, I can get a list of all other perturbagens sorted by CMap connectivity score (tau) in clue.io.

However, that is interactive, and way too tedious to retrieve connectivity scores for more than a few queries. How can I programmatically (i.e. in batch) get the connectivy score list for a perturbagen of interest?

I want to generate a matrix of all possible connectivity scores between any given shRNA knock-downs. This would be a matrix whith 3,799 x 3,799 entries with tau for any combination.

This is not feasible to do with the interactive interface. I am trying to program this and starting from the level 5 files with MODZ scores. Do I have to reproduce the method from the original paper from scratch? Or can the API or cmapR help me a bit with this?

I have contacted L1000 team via web form, received no answer, now reaching out here on GitHub.

**Comment by tnat1031** [comment]
Hi @antonkratz ,

My apologies for the delayed reply. Earlier today we sent a response to this question via the CMap team's support ticketing system, so I will close this issue here and continue the thread there.

Thanks a lot,
Ted

**Comment by antonkratz** [comment]
Thank you @tnat1031, I have received your message, let's continue via email, I will reply shortly.

**Comment by ansariom** [comment]
Hi @antonkratz ,

I have the same question! How can I get the information about the potential APIs for computing Tau?

Thanks!
Mitra
