### ISSUE TITLE
tutorial error with R-devel ... second read from gctx fails

### ISSUE THREAD

**Issue by vjcitn** [cmap/cmapR#13]
this is a heads-up concerning runnability with R-devel

following the tutorial code

```
> col_meta_path <- "GSE70138_Broad_LINCS_sig_info_2017-03-06.txt.gz"

> col_meta <- read.delim(col_meta_path, sep="\t", stringsAsFactors=F)

> # figure out which signatures correspond to vorinostat by searching the 'pert_iname' column
> idx <- which(col_meta$pert_iname=="vorinostat")

> # and get the corresponding sig_ids
> sig_ids <- col_meta$sig_id[idx]

> # read only those columns from the GCTX file by using the 'cid' parameter
> 
> 
> ds_path <- "GSE70138_Broad_LINCS_Level5_COMPZ_n118050x12328_2017-0 ..." ... [TRUNCATED] 

> vorinostat_ds <- parse.gctx(ds_path, cid=sig_ids)
reading GSE70138_Broad_LINCS_Level5_COMPZ_n118050x12328_2017-03-06.gctx
done
```
all is well.  then

```
> row_meta_from_gctx <- read.gctx.meta(ds_path, dim="row")
HDF5-DIAG: Error detected in HDF5 (1.8.19) thread 0:
  #000: H5O.c line 249 in H5Oopen(): unable to open object
    major: Symbol table
    minor: Can't open object
  #001: H5O.c line 1366 in H5O_open_name(): unable to open object
    major: Symbol table
    minor: Can't open object
  #002: H5O.c line 1407 in H5O_open_by_loc(): unable to open object
    major: Object header
    minor: Can't open object
  #003: H5Goh.c line 226 in H5O_group_open(): unable to register group
    major: Object atom
    minor: Unable to register new atom
...
```

attempt to continue session, repeating previously successful read, fails with similar errors.

This error does not occur with R 3.4 ... so it could be an issue with changes to
rhdf5 infrastructure.  I'll pass this information to the rhdf5 developer.

If you have fixes against R-devel please let me know.

The sessionInfo was

R Under development (unstable) (2017-11-08 r73690)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

Matrix products: default
BLAS/LAPACK: /app/intelMKL-2017.0.098_i86-rhel6.0/intelMKL/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cmapR_1.0           data.table_1.10.4-3 rhdf5_2.23.5       
[4] rmarkdown_1.8      

loaded via a namespace (and not attached):
 [1] compiler_3.5.0  backports_1.1.2 magrittr_1.5    rprojroot_1.3-1
 [5] tools_3.5.0     htmltools_0.3.6 Rcpp_0.12.14    stringi_1.1.6  
 [9] knitr_1.18      stringr_1.2.0   digest_0.6.13   evaluate_0.10.1
[13] Rhdf5lib_1.1.5

**Comment by grimbough** [comment]
I think this is caused by the change in behaviour of the `H5close()` function in the developmental version of **rhdf5**.  See also [https://github.com/grimbough/rhdf5/issues/6](https://github.com/grimbough/rhdf5/issues/6)

I have submitted #14 which hopefully fixes this without tying users to a particular version of R.

**Comment by tnat1031** [comment]
Thanks @vjcitn and @grimbough for the information. This is the first I've seen of this error, but agree it looks like it may have to do with the `H5close()` function. I'll see if I can reproduce on my system and suggest a fix.

**Comment by grimbough** [comment]
The pull request I submitted here is hopefully a work around so you don't have to spend too much time on it.  

Alternatively you can replace any instance of `H5close()` with `h5closeAll()`, but then you're locked into the latest version of **rhdf5**.  This works for Bioconductor packages that are tied to specific version of R, but for something available on CRAN/Github you'll need to either explicitly state the compatible versions of **rhdf5** in the DESCRIPTION file, or use some logic to pick the correct function.

**Comment by tnat1031** [comment]
Accepted PR from @grimbough , which fixes this issue. Commit 8457713.
