### ISSUE TITLE
MODZ calculation in R?

### ISSUE THREAD

**Issue by ge2sasag** [cmap/cmapR#15]
Hi,

I'm not sure if I should ask this question here, but I wonder if there is any way to calculate MODZ for a certain expression matrix (i.e., from microarray or RNA-seq) if you already have expression values calculated as robust z-score. I've been trying to do spearman pairwise correlations with cor() but I'm not sure if there's any similar code to the one available in matlab.

I want to do this because I have some expression signatures that I want to correlate with L1000 profiles in cMAP database (i.e., to do PCA) and I guess I should have my expression data calculated as MODZ prior comparison.

Thank you very much in advance.

Best
Gema

**Comment by tnat1031** [comment]
Hi Gema,

The modz algorithm is not currently available in cmapR but it's something
we've been meaning to add. This is a great reason to do it! Please look for
an update to the repository in the next couple of days.

Thanks a lot,
Ted

**Comment by ge2sasag** [comment]
Hi Ted, 

Thanks a lot! that would be really helpful! 
I look forward the update

Best
Gema

**Comment by ge2sasag** [comment]
Hi Ted! 

How is it going with the update? :)

Best
Gema

**Comment by ge2sasag** [comment]
Hi,

Any chance to have MODZ calculation in R soon? Thank you very much in advance

Best
Gema

**Comment by tnat1031** [comment]
Hi Gema,

I'm very sorry for the delay on this. We have just added the modz calculation to cmapR in the function `distil`. Please have a look and let me know if you have any questions.

Best,
Ted
