### ISSUE TITLE
cannot allocate vector of size 121.2 Gb (LINCS: level 3)

### ISSUE THREAD

**Issue by EliHei** [cmap/cmapR#16]
Hi,

I want to read whole matrix of level 3 of LINCS dataset, but it's to large to fit to my RAM. I was wondering if there is any trick (e.g., spark) to handle such large data.

**Comment by tnat1031** [comment]
Hi @EliHei,

One of the primary utilities of storing the data in GCTX format (which is based on HDF5) is that it allows one to slice out specific rows/columns from the matrix so it is not necessary to store the entire matrix in RAM. Please see `?parse.gctx` and the [cmapR tutorial](https://render.githubusercontent.com/view/ipynb?commit=28e7cbbe1eb8835115ecfb7bb8df40873750161c&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f636d61702f636d6170522f323865376362626531656238383335313135656366623762623864663430383733373530313631632f636d6170525f7475746f7269616c2e6970796e62&nwo=cmap%2FcmapR&path=cmapR_tutorial.ipynb&repository_id=86499985&repository_type=Repository#Parsing-a-subset-of-a-GCTX-file) for more details on how to specify the specific rows/columns of interest. Could you please describe in more detail what you'd like to do with the data?

Thanks a lot,
Ted

**Comment by EliHei** [comment]
@tnat1031 

Thanks for your response. In order to train a neural network, I want data as a dataframe.

**Comment by tnat1031** [comment]
@EliHei 

Ok, in that case you may need to do some manual wrangling of the data. You could parse a subset of the file as a GCT object and then convert the matrix to a data.frame (using `as.data.frame` or something similar). I'd recommend prototyping that on a subset of the data first to get a sense for whether the inputs are correct and the NN results are making sense. Once you've got that working, you could try scaling up using something like [sparkR](https://spark.apache.org/docs/latest/sparkr.html), though I must admit I haven't tried it myself and am not sure whether is supports NN directly.

Could you tell us more about what you'd like the NN to do?

Thanks,
Ted

**Comment by EliHei** [comment]
Thanks  @tnat1031! 

I want to use NN in order to check something about PCLs (as a supervised task). 
I have tried sparkR, manipulating/merging subsets of data of Level 2, but still have some problems according to my limited ram. Do you have any idea, how to handle data from level 2 for normalizing and omitting NAs? (I mean when data is in GCT format.)

**Comment by in4matx** [comment]
>
> I want to use NN in order to check something about PCLs (as a supervised
> task).


Good idea.

But why don't you start with level 4 or level 5 data as provided rather
than descend to more primitive forms.

**Comment by EliHei** [comment]
I prefer to use only Landmark genes. Therefore, I need to normalize expression data of landmark genes, myself.
@in4matx

**Comment by in4matx** [comment]
You can still extract just the lm genes from the provided level 4 or 5 data.

Note that normalization doesn't in itself depend on inferred or not.

Anyway, just suggesting a path by which you can get to your core use case
(prediction) quicker.

Good luck.

aravind

**Comment by EliHei** [comment]
@in4matx 
Thank you very much!

So for example, in level 3 (or 4/5) of data, the normalized expression of lm genes is just according to lm genes rather than both lm and inferred genes. Am I right? (if so, I will be very happy!)

**Comment by in4matx** [comment]
>
> So for example, in level 3 (or 4/5) of data, the normalized expression of
> lm genes is just according to lm genes rather than both lm and inferred
> genes. Am I right? (if so, I will be very happy!)


Yes, to confirm, inference or the lack thereof has *no* impact on
normalization of the landmarks. Extract and use those from 4/5
