### ISSUE TITLE
`write.gctx` for incremental output

### ISSUE THREAD

**Issue by luyoutao** [cmap/cmapR#18]
Dear developers,

Thanks for developing this software. I wonder if the output function `write.gctx` supports incremental save, so that there is no need to create a GCT object containing full data set in memory. Thanks.

**Comment by tnat1031** [comment]
Hi @foehnwind,

Thanks for using this package. `write.gctx` does not yet support
incremental output but it's something that we're planning to add. Please
stay tuned.

Best,
Ted
