### ISSUE TITLE
Documentation doesn't include a download link

### ISSUE THREAD

**Issue by lachlansimpson** [cmap/cmapR#20]
The documentation [here](https://clue.io/cmapR/)  doesn't include a link to a file or file repository.

**Comment by tnat1031** [comment]
Hello,

The link to the GitHub project under the 'Other Resources' heading will
take you to the GitHub repository where you can get the source code.

Best,
Ted

**Comment by lachlansimpson** [comment]
Glad you have it all sorted then - good luck with your project.
