### ISSUE TITLE
Error reading GCT downloaded from CLUE

### ISSUE THREAD

**Issue by concatenize** [cmap/cmapR#21]
Hi CMap team,

I am trying to access results from a CMap batch query. I downloaded them and read them into R using `cmapR::parse.gctx( my_gct_path )`, but `parse.gctx` errs, saying `invalid class “GCT” object: cid must be unique`. I don't want to upload the whole file, but I find I can reproduce the error with just the head:

[demo.txt](https://github.com/cmap/cmapR/files/2368499/demo.txt)

Is the error because of all the `...` in the metadata? Is this file (the start of) a valid GCT file? 

Thanks for your help! I'm really excited to try using CMap on my data.

**Comment by concatenize** [comment]
I replaced the third line with duplicate-free column IDs and it works now. I assume this is an issue with the download, not the R package, so I am closing this issue and I'll contact support for the CMap website.

**Comment by tnat1031** [comment]
Thanks and sorry for the delayed response. The issue is indeed with the
truncated cids in your file, which with the ... are read as duplicates.
Will pick up the thread via the CMap support system.
