### ISSUE TITLE
parse.gctx fails to work unless user explicitly import rhdf5

### ISSUE THREAD

**Issue by nzllim** [cmap/cmapR#22]
Contrary to prior behaviour, where cmapR auto-magically imports `rhdf5`, in the latest iteration, it fails to do so, and when executing parse.gctx, it returns with an error:

> Error in h5closeAll() : could not find function "h5closeAll"

For the uninitiated, they may not realize this is an `rhdf5` function, which wouldn't be great for first-time users.

**Comment by tnat1031** [comment]
Hi @nzllim, could you please provide more details about the exact commands you are executing? parse.gctx should work without having to explicitly import rhdf5. The following code should work as written.

```R
library(cmapR)
foo <- parse.gctx("/path/to/gctx/file.gctx")
```

**Comment by nzllim** [comment]
Hi @tnat1031,
Strangely enough that is exactly what I did, and it failed. The order of execution was such:
`library(data.table)`
`library(cmapR)`
`a = parse.gctx('Level3.gctx')`

Snippets of SessionInfo():
R version: 3.5.0
OS: CentsOS 7 x64.
All latest versions of data.table, cmapR, rhdf5 and their related dependencies.

**Comment by nzllim** [comment]
@tnat1031,
I just inspected cmapR's code and I suspect this might be what that is causing the code to fail:
Line 503, `https://github.com/cmap/cmapR/blob/master/R/io.R`

`h5closeAll()` should be `rhdf5::h5closeAll()`

Some work might be needed to inspect for other hidden namespace issues similar to this ...

**Comment by tnat1031** [comment]
Thanks @nzllim. I just added some minor tweaks to address this specific issue.
