### ISSUE TITLE
parse.gctx() dimnames error

### ISSUE THREAD

**Issue by rboiarsky** [cmap/cmapR#23]
I am getting an error in parse.gctx() which I can't figure out.
I run `parse.gctx("../fpkm_limit_baseline_cd138.gct")` and get this error:

> parsing as GCT v1.2
> ../fpkm_limit_baseline_cd138.gct 55861 rows, 770 cols, 0 row descriptors, 0 col descriptors
> Error in dimnames(mat) = list(rid, cid) : 
>   length of 'dimnames' [2] not equal to array extent
> In addition: Warning messages:
> 1: In matrix(mat, nrow = nrmat, ncol = ncmat + nrhd + col_offset, byrow = TRUE) :
>   data length [43068831] is not a sub-multiple or multiple of the number of columns [772]
> 2: In matrix(as.numeric(mat[, (1 + col_offset):ncol(mat)]), nrow = nrmat,  :
>   NAs introduced by coercion

Any ideas how to get past this? My file is a gct not gctx file. It's extension is .gct, and here is a snapshot of the first few rows/columns:

![image](https://user-images.githubusercontent.com/19732554/47190473-9ace9480-d30f-11e8-9bad-45e6aaa79d21.png)

I am using cmapR version 1.0.1, and here is my session info:

> $platform
> [1] "x86_64-apple-darwin15.6.0"
> 
> $arch
> [1] "x86_64"
> 
> $os
> [1] "darwin15.6.0"
> 
> $system
> [1] "x86_64, darwin15.6.0"
> 
> $status
> [1] ""
> 
> $major
> [1] "3"
> 
> $minor
> [1] "5.1"
> 
> $year
> [1] "2018"
> 
> $month
> [1] "07"
> 
> $day
> [1] "02"
> 
> $`svn rev`
> [1] "74947"
> 
> $language
> [1] "R"
> 
> $version.string
> [1] "R version 3.5.1 (2018-07-02)"
> 
> $nickname
> [1] "Feather Spray"

**Comment by tnat1031** [comment]
Hi Rebecca,

It looks to me like perhaps the gct file you're using doesn't strictly
conform to the GCT v1.2 spec, but I can't see anything obviously wrong with
it from the screenshot. Is there any chance you could send me or point me
to the the file so I could do some testing?

Thanks a lot,
Ted

**Comment by rboiarsky** [comment]
Thank you, @tnat1031 ! Here is a link to the gct file: https://www.dropbox.com/s/vs8503sziwqb0cq/fpkm_limit_baseline_cd138.gct?dl=0

**Comment by tnat1031** [comment]
Hi Rebecca,

Thanks for pointing me to the file. After taking a closer look, I think
there are a couple issues. One is that the number of data columns in the
file appears to be 769, but in the header (second row of file) this is
indicated as 770. The other is that two of the row ids seem to be
duplicated. These row is are "1-Mar" and "2-Mar'. My suspicion is that
these are gene symbols that were auto-converted to dates by a program like
excel. Do you know if this is how the file was created? Changing the number
of columns and de-duplicating the row ids should enable you to parse the
file using `parse.gctx`. Can you please let me know if that works for you?

Thanks a lot,
Ted
