### ISSUE TITLE
cmapR in CRAN or Bioconductor

### ISSUE THREAD

**Issue by nuno-agostinho** [cmap/cmapR#24]
I need to parse GCTX files in my own BIoconductor package, but their guidelines only allow to depend on packages available on CRAN and Bioconductor.

As a workaround, I directly include your code to parse those GCTX files, while crediting your GitHub repository for that part of the code in the documentation of the respective functions. However, I would much prefer if you could publish your package so I could simply use the functions I need.

Do you have any plans on distributing cmapR through either CRAN or Bioconductor? Thank you!

**Comment by tnat1031** [comment]
H Nuno,

Yes we do have plans to distribute cmapR through both CRAN and
Bioconductor, probably in that order. I'm not sure of the exact timeline
but hopefully within the next month or so.

Thanks very much,
Ted

**Comment by nuno-agostinho** [comment]
@tnat1031, it is great to hear that, thank you! :)

**Comment by nuno-agostinho** [comment]
@tnat1031, after re-reading your comment, I would just like to warn you that you cannot submit your package to both CRAN and Bioconductor. As according to [Bioconductor's Package submission](http://bioconductor.org/developers/package-submission/):
> *Bioconductor* Packages should (...) Not exist on CRAN. A package can only be submitted to one or the other.

Given this restriction, I would say that Bioconductor is a more appropriate repository than CRAN for cmapR since your package is related to bioinformatics.

**Comment by tnat1031** [comment]
Oh, thanks for the heads up! Is this a new Bioconductor policy. I wasn't
aware. But I agree if we must choose one then Bioconductor is more
appropriate.

**Comment by gwaybio** [comment]
@shntnu and I bumping into this issue today - would love to get this package on bioconductor (and subsequently bioconda) to enable fully reproducible workflows! Thanks!

**Comment by tnat1031** [comment]
My apologies this hasn't been addressed yet. Will try to do it asap.

**Comment by tnat1031** [comment]
Sorry for the delay on this, but cmapR has finally been accepted into Bioconductor: https://www.bioconductor.org/packages/release/bioc/html/cmapR.html
