### ISSUE TITLE
parse.gctx error

### ISSUE THREAD

**Issue by ibilgen** [cmap/cmapR#26]
I'm using GSE92743_Broad_Affymetrix_training_Level3_Q2NORM_n100000x12320.gctx file. I can successfully read the file using RStudio in Linux. The problem occurs when I run the source code containing a call for parse.gctx function by using Rscript command in linux terminal. The error is shown below.

 $ Rscript thecode.R

Error in initialize(value, ...) :
  invalid names for slots of class “GCT”: set_annot_rownames, matrix_only
Calls: source ... <Anonymous> -> <Anonymous> -> initialize -> initialize
Execution halted

I call the parse.gctx in the source code as follows 
parse.gctx(fname = ds_file, rid = dataidx$testidx, matrix_only = T)

It'is totally running in RStudio, I used several times. But in linux terminal, I got that error. Why is the reason?

**Comment by tnat1031** [comment]
Hi @ibilgen,

To make sure I understand, you're saying the file parsing works fine in
RStudio but NOT when launching an R session from your terminal? And it's
exactly the same code each time? The code you have included so far looks
fine to me. Would you be able to share the rest of your script so that I
can see if there is anything else that might be causing the issue?

Thanks a lot,
Ted

**Comment by ibilgen** [comment]
To clarify, 

There is no problem when I launch the R session from terminal and run the code like: 
$ R
> source("the_code.R")

The problem occurs when I run it as follows:
$ Rscript the_code.R 

----
The rest of the code is not related to cmapR, except the following part . This code is also running with no issue regardless of how I start it. 

#Reading IDs
ds_file = "../data/GSE92743_training_transformed.gctx_n12320x100000.gctx"
sample.ids = read.gctx.ids(gctx_path = ds_file, dimension = "row")
gene.ids = read.gctx.ids(gctx_path = ds_file, dimension = "column")

----
Only the parse.gctx throws the error I reported. By the way, I used the parse.gctx many times  by launching the code like "Rscript the_code.R" in a different linux machine, it gave no error. But this time, I am running on a different linux machine and it gives that error.

----
Edit

R CMD BATCH command worked unlike Rscript command.  Namely, parse.gctx function worked fine.
The whole command is:
R CMD BATCH '--args begidx=1 endidx=1000' perturb_test_batch.R &

**Comment by tnat1031** [comment]
Hm, that code looks ok to me. Could you please run `sessionInfo()` on the
problematic linux machine and send the output? Thanks

**Comment by ibilgen** [comment]
When I run it via Rscript it print out:
**$ Rscript the_code.R 3 4**
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=tr_TR.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=tr_TR.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=tr_TR.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=tr_TR.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  base

loaded via a namespace (and not attached):
[1] compiler_3.4.4

2019-02-07 09:55:45.902301: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Autoencoder is rebuilt..
Reading input data..
Error in initialize(value, ...) :
  invalid names for slots of class “GCT”: set_annot_rownames, matrix_only
Calls: source ... parse.gctx -> <Anonymous> -> initialize -> initialize
Execution halted
```
When I run it in RStudio, I realized that it prints everything same but except "attached base packages" and "loaded via a namespace (and not attached)"

RStudio print out:
**> sessionInfo()**
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

**attached base packages:**
[1] stats     graphics  grDevices utils     datasets  **methods**   base     

**loaded via a namespace (and not attached):**
[1] compiler_3.4.4 tools_3.4.4    **yaml_2.2.0**
```

It looks that "methods" and "yaml_2.20" are apsent in RScript run.

**Comment by tnat1031** [comment]
I'm sorry, but I'm not sure what is causing the error. I haven't
encountered this before. Some things I can think of that might help us
debug:

1. Try parsing a different GCTx file so we can see whether the problem is
specific to the file you're currently using.
2. Clone the cmapR source code from github and run R CMD check to see if
that throws any errors.
3. Try re-installing the cmapR package
