### ISSUE TITLE
Error in parse.gctx(gct_file, matrix_only = TRUE) :    could not find function "parse.gctx", error message shows up for all other functions too

### ISSUE THREAD

**Issue by Jimmay13** [cmap/cmapR#28]
I recently spent 8+ hours trying to get your package functions to work.  At first, all that worked was the parse.gctx function.  After reinstalling your package and the other packages necessary, now the parse.gctx function doesnt work either.  

library(cmapR)
library(rhdf5)
gct_file <-  system.file("/Users/jamesordaya/Downloads/GinnysBioinformaticsFolder/GSE70138_Broad_LINCS_Level3_INF_mlr12k_n78980x22268_2015-06-30.gct", package="cmapR")
(ds <- parse.gctx(gct_file, matrix_only=TRUE))
print(my_ds) is my code.  I also tried all other functions which get a similar error message

"Error in parse.gctx(gct_file, matrix_only = FALSE) : 
  could not find function "parse.gctx""

I dont know what to do.  I must be honest, I am still pretty new to R developer packages from GitHub so I may need a bit more direction than others but, like I said, I was able to get the parse function to work before the reinstall and now it has the same errors all the other functions had before (and afterwards).

**Comment by tnat1031** [comment]
Hi @Jimmay13 ,

Thanks for using this package and my apologies for the delayed reply. Seems like perhaps there is an issue with the cmapR install. Does the code

```R
library(cmapR)
```

work successfully? If so, can you please also run this and post the output:

```R
find.package("cmapR")
```

Thanks,
Ted

**Comment by felon02** [comment]
i met the same problem with Jimmay13. here's my input, output and my R version:
![image](https://user-images.githubusercontent.com/30990200/72582937-5f11e880-391f-11ea-80b1-e59da177317d.png)

**Comment by tnat1031** [comment]
Hi @felon2, @Jimmay13,

My apologies for the confusion. We're in the process of submitting to
Bioconductor and have changed the some of the function naming conventions
to comply with their standards. Function names that used to contain '.'
have been replaced with '_'. Hence, parse.gctx is now parse_gctx and so on.
Please try that and see if it works. There is additional info and examples
in the vignettes/tutorial.Rmd.

Thanks a lot,
Ted
