### ISSUE TITLE
Readthedocs page gives a 404

### ISSUE THREAD

**Issue by bsiranosian** [cmap/cmapR#31]
This link is dead for me https://clue.io/cmapR/index.html

**Comment by tnat1031** [comment]
thanks, will look into it

**Comment by bsiranosian** [comment]
As a side note, I've been using  cmapR in my new lab, primarily for taxonomic classification of metagenomic samples. It's really helpful for keeping the taxonomy (Domain, phylum, class, order... etc) along with the data matrix!

**Comment by tnat1031** [comment]
Excellent, glad to hear it! Hope things are well with you
