### ISSUE TITLE
Installing cmapR requires R >= 4.0

### ISSUE THREAD

**Issue by ceiron61** [cmap/cmapR#51]
Hello,

I'm trying to install cmapR on R 3.6.2 and I get this error:

> devtools::install_github("cmap/cmapR")
Downloading GitHub repo cmap/cmapR@master
✓  checking for file ‘/tmp/RtmpUSPwSG/remotes10de422e46bd/cmap-cmapR-f4d3879/DESCRIPTION’ ...
─  preparing ‘cmapR’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘cmapR_0.99.18.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
Installing package into ‘/home/ferreen2/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
ERROR: this R is version 3.6.2, package 'cmapR' requires R >= 4.0
Error: Failed to install 'cmapR' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpUSPwSG/file10de472bd25dd/cmapR_0.99.18.tar.gz’ had non-zero exit status

As of today, R 4.0 has not even be released yet.
Can you please let me know how can I install the package on R 3.6.2?

Thank you,
Enrico

**Comment by tnat1031** [comment]
Hi Enrico,

Sorry for the confusion about this. We're in the process of submitting
cmapR to Bioconductor, which requires R 4.0, so we needed to temporarily
update the requirements to get it to build on their system. I've changed
the requirements in the source code now to require R >= 3.5. Could you
please try again to install?

Thanks a lot,
Ted

**Comment by ceiron61** [comment]
Thank you Ted - it works now!

**Comment by hsiaoyi0504** [comment]
It seems to me that I have the same issue again.

**Comment by tnat1031** [comment]
Hi @hsiaoyi0504,

Sorry you are having trouble with package. Can you please let me know how you are trying to install it? Are you installing from Bioconductor (recommended) or directly from github? Are you using R >= 4.0?

Thanks a lot,
Ted

**Comment by hsiaoyi0504** [comment]
@tnat1031 Sorry for the late reply. I was using R 3.6 and `renv`.
It seems to me that I successfully installed the package later using the R3.6 branch, but is this documented at any place?
Probably I didn't find it.

**Comment by tnat1031** [comment]
Hi @hsiaoyi0504,

No worries. I don't think that's documented anywhere, but it will work if you need to use R < 4.0. If possible, it might be advisable to use R > 4.0 to that you have access to the latest package versions, updates, etc.

Thanks a lot,
Ted
