### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by monabiyan** [cmap/cmapR#52]
Hi I also got this installation error, I used to be able to install and use it with no problem. Thank you!

Error: Failed to install 'cmapR' from GitHub:
  (converted from warning) unable to access index for repository https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.6/PACKAGES'

**Comment by tnat1031** [comment]
Hi @monabiyan ,

That seems like it might be an issue with the repository configuration in your RStudio. Can you try installing the package using

`devtools::install_github('cmap/cmapR')` ?

and let me know if that works? Thanks

**Comment by monabiyan** [comment]
Thank you so much. That worked!
