### ISSUE TITLE
Changing version during write_gct causes "unrecognised format specification '%'"

### ISSUE THREAD

**Issue by gerardq675** [cmap/cmapR#55]
I identified an error in io.R, that was preventing me from writing out a 1.2 gct file;

`Error in sprintf("#1.%d\n%d\t%", ver, nr, nc) : 
  unrecognised format specification '%'`

Code:
`sprintf("#1.%d\n%d\t%", ver, nr, nc)`

Is missing the d after the %:

`sprintf("#1.%d\n%d\t%d", ver, nr, nc)`

It works for me now, I hope this helps!

**Comment by tnat1031** [comment]
good catch, thanks @gerardq675 ! I just pushed a fix and corresponding test
