### ISSUE TITLE
Annotating level 3 or level 4 data

### ISSUE THREAD

**Issue by Joker-Jerome** [cmap/cmapR#57]
Hi there, 

Thanks for sharing the code and it works perfectly for me in terms of manipulating the level 5 data. When I was trying to use the level 3 or level 4 data, it seems that I couldn't find a good source for the annotation file. I was wondering where I can find those annotation files so that I can use other levels of data. 

Thanks in advance!

Best,
Jerome

**Comment by tnat1031** [comment]
Hi Jerome,

You can find that annotation file in our GEO repository:
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE92742

The file GSE92742_Broad_LINCS_inst_info.txt.gz contains the
experimental (column) annotations for level 3 and 4 data.

Best,
Ted
