### ISSUE TITLE
Some questions about function parse_gctx

### ISSUE THREAD

**Issue by XiaohanChen97** [cmap/cmapR#58]
Hi Ted,

I met some error in reading GSE92743_Broad_OLS_WEIGHTS_n979x11350.gctx. 
Do you ever meet this kind error or have some advice about this.
Below is my code:

> source("/tools/R_pakages/master/cmapR/R/GCT.R")
in method for "coerce" with signature "GCT","SummarizedExperiment": no definition for class 
 “SummarizedExperiment”
> source("/tools/R_pakages/master/cmapR/R/io.R")
> source("/tools/R_pakages/master/cmapR/R/utils.R")
> source("/tools/R_pakages/master/cmapR/R/data.R")
> coef_set <-parse_gctx("/GSE92743_Broad_OLS_WEIGHTS_n979x11350.gctx")
reading /GSE92743_Broad_OLS_WEIGHTS_n979x11350.gctx
Error: Unable to read dataset.
Not all required filters available.
Missing filters: deflate

Thank you,
Chen

**Comment by tnat1031** [comment]
Hi Chen,

I haven't seen that exact error before, but it could be due to the fact
that you are sourcing the cmapR package files instead of formally
installing the package. Is there a reason for that? cmapR is now available
on Bioconductor, so you can install from there:
https://www.bioconductor.org/packages/release/bioc/html/cmapR.html

That should enforce that the cmapR dependencies are also installed, which I
think should solve the problem for you. Can you please give that a try and
let me know if it works?

Best,
Ted

**Comment by XiaohanChen97** [comment]
Hi Ted,

The same error appeared after installing cmapR by BiocManager.There may be some problems in my system.
Finally, I downloaded the python version of the tools and successfully read the data.
In general, thank you very much for your suggestions and help.

Best,
Chen

**Comment by tnat1031** [comment]
Hi Chen,

Glad you got the python version working but sorry that cmapR still
isn't working for you. Do you get the same error with other GCTX files or
is it just this one?

Best,
Ted

**Comment by XiaohanChen97** [comment]
Hi Ted,

I have successfully parsed other GCTX files before. So maybe there are some differences in that file. 

Best,
Chen

**Comment by tnat1031** [comment]
Hi Chen,

Ok that's good to know. I think it probably is something with that file.
Can you check that it has been properly decompressed? Can you please run
`file GSE92743_Broad_OLS_WEIGHTS_n979x11350.gctx` and share the output?

Thanks a lot,
Ted

**Comment by XiaohanChen97** [comment]
Hi Ted,

I have run the command, and got the right result:
`file GSE92743_Broad_OLS_WEIGHTS_n979x11350.gctx
GSE92743_Broad_OLS_WEIGHTS_n979x11350.gctx: Hierarchical Data Format (version 5) data`.
Maybe you can read the file in your R and see if it will work. 
Then this will tell is there something wrong in the file, in the cmapR or in my configuration.

Best,
Ted

**Comment by tnat1031** [comment]
Ok thanks, that looks right to me. Yes, I am able to parse the file
successfully on my system, so I do think it may be an issue with your
configuration. Nevertheless, it is odd that only this file seems affected.
Perhaps it was corrupted somehow during download? You could try downloading
again to see if that helps.

Best,
Ted

**Comment by XiaohanChen97** [comment]
Hi Ted,

I can almost be sure that there are some problems with my system configuration. Because I have successfully used the file for some work by python.
Anyway, thank you very much for your help these days. And you are really a good person and totally a responsible author.

Best,Chen

**Comment by tnat1031** [comment]
Hi Chen,

Thanks very much for the kind words and please let me know if there's
anything else I can do to help debug the issue.

Best,
Ted
