### ISSUE TITLE
suggestion on simple installation

### ISSUE THREAD

**Issue by hakyim** [cmap/cmapR#6]
It may be even easier to install using devtools:

> install.packages("devtools") ## if needed
> devtools::install_github("cmap/cmapR")

**Comment by tnat1031** [comment]
Good point, thank you! Will update the instructions.

**Comment by jananiravi** [comment]
Hello @tnat1031 , installing cmapR on the latest version of R/RStudio doesn't seem to work anymore. Could you please suggest alternatives (in R/shell) to work with the GCTx data format? Thank you!

```
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray         
```

**Comment by tnat1031** [comment]
Hi Janani,

Can you please post the command(s) you ran and the error produced so I can
try to troubleshoot? Thanks!

**Comment by jananiravi** [comment]
Thanks for your quick response, @tnat1031 I have trouble with `cmapR` installation in the latest version of R (version details incl. above). I get the following errors.

```
devtools::install_github("cmap/cmapR")
Downloading GitHub repo cmap/cmapR@master
Error in getrootdir(untar(src, list = TRUE)) : 
  length(file_list) > 0 is not TRUE
```

```
install.packages("cmapR")
Installing package into ‘/Google_Drive/GitHub’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘cmapR’ is not available (as a binary package for R version 3.5.1)
```

**Comment by jananiravi** [comment]
@tnat1031 thanks again for your help earlier today.

I'm getting some of my students to test this standalone script to install cmapR and report issues if any. You could likely add this to the repo until the `dependencies=T` alone suffices.

```
## Installing dependencies
install.packages("data.table")

install.packages("BiocManager") # to install rhdf5
BiocManager::install("rhdf5", version = "3.8")

install.packages("devtools") # if you don't have it

## Installing cmapR
devtools::install_github("cmap/cmapR", dependencies=T, force=T)
```

**Comment by tnat1031** [comment]
Great, thanks Janani. Does this script work for you?

**Comment by jananiravi** [comment]
I am guessing that it does work @tnat1031 My student who's very new to R installed it with this! The script worked with one of the new R projects we created w/ packrat as well. I will get you more feedback within a day or two. Please let me know if this works alright w/ your projects+packrat too. thanks!

**Comment by tnat1031** [comment]
Ok great, thanks for adding to the repo!

**Comment by jananiravi** [comment]
The error in the main project w/ packrat remains unless I load it as an external package (packrat settings). I tried it with both `devtools::install_github` & `remotes::install_github`, just in case.

```
Downloading GitHub repo cmap/cmapR@master
Error in getrootdir(untar(src, list = TRUE)) : 
  length(file_list) > 0 is not TRUE
```
