### ISSUE TITLE
page is missed

### ISSUE THREAD

**Issue by FADHLyemen** [cmap/cmapR#60]
Hi, 
I used to use the below link but now could not access it:
https://github.com/cmap/cmapR/blob/master/cmapR_tutorial.ipynb

Could you help?
It was describe more details about GSE70138 data

**Comment by tnat1031** [comment]
Hi @FADHLyemen ,

Very sorry for the delayed reply. This ipynb tutorial has been removed and replaced with the file here:
https://github.com/cmap/cmapR/blob/master/vignettes/tutorial.Rmd

It doesn't explicitly cover working with the GSE70138 data, but it does illustrate common use cases. Please let me know if you have specific questions and I can try to help.

Thanks a lot,
Ted
