### ISSUE TITLE
Prada dependency error

### ISSUE THREAD

**Issue by marcstein** [cmap/cmapR#63]
I apologize if this has been addressed previously, but I couldn't find it mentioned in the closed or open issues.

BiocManager::install("cmapR")

returns

ERROR: dependency ‘prada’ is not available for package ‘cmapR’

Same outcome with devtools. Tried a direct install of Prada as well.

Any suggestions? 

Thanks!

Marc

**Comment by tnat1031** [comment]
Hi @marcstein, 

I think this may be due to the fact that the prada package has been deprecated. I'll need to update cmapR to remove the dependency. Could you please also share your session info?

Thanks a lot,
Ted

**Comment by marcstein** [comment]
Hi Ted,

I just made an interesting discovery that might help. With R 4.0 the
install fails. I downgraded my R to 3.6.3 and it installed. I'll try to
find a machine still running 4.0 and generate a sessionInfo from a failed
instance.

Thanks for the quick response!

Best,

Marc



Marc Stein CEO
underwrite.ai
P. (617) 545-7171   M. (857) 222-3291
E. marc.stein@underwrite.ai
W. https://www.underwrite.ai
<https://www.linkedin.com/in/marc-stein-b83b765>

**Comment by marcstein** [comment]
Here is the error from 4.0.3

Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)
Installing package(s) 'cmapR'
Warning: dependency ‘prada’ is not available
trying URL '
https://bioconductor.org/packages/3.12/bioc/src/contrib/cmapR_1.2.0.tar.gz'
Content type 'application/x-gzip' length 4037350 bytes (3.9 MB)
==================================================
downloaded 3.9 MB

ERROR: dependency ‘prada’ is not available for package ‘cmapR’
* removing ‘/usr/local/lib/R/4.0/site-library/cmapR’

The downloaded source packages are in
‘/private/var/folders/3n/0tgfqb1x5pzfrxt0b0wd1bkr0000gn/T/Rtmp3qhC2Y/downloaded_packages’
Warning message:
In install.packages(...) :
  installation of package ‘cmapR’ had non-zero exit status

Here is the sessionInfo

R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin20.1.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /usr/local/Cellar/r/4.0.3/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10 compiler_4.0.3      tools_4.0.3

Thanks!



Marc Stein CEO
underwrite.ai
P. (617) 545-7171   M. (857) 222-3291
E. marc.stein@underwrite.ai
W. https://www.underwrite.ai
<https://www.linkedin.com/in/marc-stein-b83b765>

**Comment by marcstein** [comment]
Here is the sessionInfo from 3.6.3 that works

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.16

Matrix products: default
LAPACK:
/Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] cmapR_0.99.19

loaded via a namespace (and not attached):
 [1] XVector_0.26.0              GenomicRanges_1.38.0
 BiocGenerics_0.32.0         zlibbioc_1.32.0             MASS_7.3-51.4

 [6] IRanges_2.20.2              BiocParallel_1.20.1
lattice_0.20-38             rrcov_1.5-5                 pcaPP_1.9-73

[11] GenomeInfoDb_1.22.1         tools_3.6.0
SummarizedExperiment_1.16.1 parallel_3.6.0              grid_3.6.0

[16] Biobase_2.46.0              matrixStats_0.57.0          Matrix_1.2-17
              GenomeInfoDbData_1.2.2      prada_1.62.0
[21] BiocManager_1.30.10         RColorBrewer_1.1-2
 S4Vectors_0.24.4            bitops_1.0-6                RCurl_1.98-1.2

[26] robustbase_0.93-6           DelayedArray_0.12.3         DEoptimR_1.0-8
             compiler_3.6.0              stats4_3.6.0
[31] mvtnorm_1.1-1

Marc Stein CEO
underwrite.ai
P. (617) 545-7171   M. (857) 222-3291
E. marc.stein@underwrite.ai
W. https://www.underwrite.ai
<https://www.linkedin.com/in/marc-stein-b83b765>

**Comment by tnat1031** [comment]
Ok great, thanks very much. I think this is because prada is deprecated in
the latest bioconductor release so I'll need to remove that dependency.
I'll try to do that as soon as I can but in the meantime if you're able to
use an earlier version of R hopefully that can serve as a short term
workaround.

Thanks again,
Ted

**Comment by ItoLabRoswellPark** [comment]
exact same issue here with prada. thank you for working on removing the dependency

**Comment by SBata** [comment]
very same issue here with prada.
thank you for working on removing the dependency.
if it needs the `exprs` and `readFCS` functions, why not getting them from `flowCore`?

**Comment by marcstein** [comment]
If you can downgrade to R 3.6.3 it works.

Best,

Marc

Marc Stein CEO
underwrite.ai
P. (617) 545-7171   M. (857) 222-3291
E. marc.stein@underwrite.ai
W. https://www.underwrite.ai
<https://www.linkedin.com/in/marc-stein-b83b765>

**Comment by tnat1031** [comment]
Thanks both. I'm working on this now and should have a fixed pushed in the
next day or two.

Best,
Ted

**Comment by tnat1031** [comment]
Hi @marcstein @SBata ,

I have made changes and pushed to the development branch of bioconductor: https://bioconductor.org/packages/3.13/bioc/html/cmapR.html

I believe that this should fix the issue, if you are able to try installing the package from there.

Thanks a lot,
Ted
