### ISSUE TITLE
Questions about connectivity map

### ISSUE THREAD

**Issue by lovenicole** [cmap/cmapR#66]
Hi. I had a few questions about the Connectivity map, so I contacted the Broad Institute several times through the `Contact us` session of clue.io but I couldn't get any answer from it. Thus I'm addressing an issue here. Here're my questions below. 

1. There are only 8,969 perturbagens in Touchstone version 1.0 even though there are 51,219 perturbagens in LINCS phase I (GSE92742) data. I think it's because those perturbagens are well annotated with MOAs and protein targets so they're included in the Touchstone reference data. Is it right?

2. How did you collapse the replicates of a perturbagen into a signature, if it was tested in several time points and several doses? In order to understand how, I've read your paper (Subramanian A, Narayan R, Corsello SM, et al. A Next Generation Connectivity Map: L1000 Platform and the First 1,000,000 Profiles. Cell. 2017;171(6):1437-1452.e17. doi:10.1016/j.cell.2017.10.049) and `Connectopedia` session in clue.io but I got no information except for information on the process how to collapse the replicates into a signature, which are tested in the same condition (dose and duration of treatment). 

3. It's not working to analyze in the latest version of Touchstone. The 1.0 version of Touchstone works well with the same query as I did in the latest version. The same Error message keeps popping up and it says it may be because of the memory problem. 

Due to time lag, I cannot participate in the zoom meetings held during your work hours. Please understand me addressing an issue like this.
Any information you could give me that sheds light on these important issues would be greatly appreciated.

**Comment by tnat1031** [comment]
Hi @lovenicole,

Sorry that we didn't get your message through clue.io. I'll respond to your email directly, as these questions are not directly related to the cmapR package.

Thanks a lot,
Ted

**Comment by Pweidemueller** [comment]
Hi Ted (@tnat1031),

I actually have the very same question as @lovenicole. I've send an Email via the clue.io website as well and hope to receive a reply soon. In the meantime, I know the cmapR github is not the right place for this issue, but maybe the CMap team could include the answer in an entry on Connectopedia?

**Comment by tnat1031** [comment]
Hi @Pweidemueller,

Sorry that you haven't yet gotten a response via the clue system. I found your ticket there and will reply via that system so our team has a record of the correspondence. Your suggestion to update connectopedia with some of this content is a good one and we'll do that as well.

Thanks a lot,
Ted
