### ISSUE TITLE
Level 4 replicates do not match a specific Level 5 signature

### ISSUE THREAD

**Issue by afaissa** [cmap/cmapR#71]
I am trying to plot some genes using data level 4 for my compound (BRD-K55591206) on HepG2 cells.

There are two signatures with HepG2 cells at level 5:
LJP008_HEPG2_24H:J01
POL001_HEPG2_24H:J09
To make sure I was using the same data from these level 5 signatures I checked the replicates at level 4 of each of these signatures above. The average of the two LJP008 experiments (distil_ids: LJP008_HEPG2_24H_X2_B20:J01|LJP008_HEPG2_24H_X3_B20:J01) matches the signature of each gene at level 5. **Perfect**.

**However**, the level 4 data for signature POL001_HEPG2 (distil_ids: POL001_HEPG2_24H_X1.L2_B23:J07|POL001_HEPG2_24H_X2.L2_B23:J07|POL001_HEPG2_24H_X3.L2_B23:J07) **does not match level 5**.

If we use the NAT2 gene as an example, we have the following level 5 value: 0.004413

On the other hand, the values for the level 4 replicates are:
POL001_HEPG2_24H_X1.L2_B23:J07 = -0.386299998
POL001_HEPG2_24H_X2.L2_B23:J07 =  0.110600002
POL001_HEPG2_24H_X3.L2_B23:J07 =0.38409999
**The avg 0.036133 does not match level 5 0.004413**

The compound is BRD-K55591206, 10 µM, 24 h.

**Why don’t they match?**

I am using cmapR to retrieve the data from these files:
https://clue.io/releases/data-dashboard
https://s3.amazonaws.com/macchiato.clue.io/builds/LINCS2020/level5/level5_beta_trt_cp_n720216x12328.gctx
https://s3.amazonaws.com/macchiato.clue.io/builds/LINCS2020/level4/level4_beta_all_n3026460x12328.gctx
https://s3.amazonaws.com/macchiato.clue.io/builds/LINCS2020/siginfo_beta.txt
https://s3.amazonaws.com/macchiato.clue.io/builds/LINCS2020/instinfo_beta.txt

Thank you,
Alex

**Comment by tnat1031** [comment]
Hi @afaissa,

Thanks for reaching out. The procedure for computing level 5 from level 5 is actually a weighted average (not the standard arithmetic mean). Each replicate is weighted according to its average correlation with the others (correlations computed on all 978 landmark genes). When there are only 2 replicates, as in LJP008_HEPG2_24H:J01, the weighted average is equivalent to the arithmetic mean. When there are more than 2 replicates, as in POL001_HEPG2_24H:J09, it is not. You can read more about the procedure in the methods section of this article: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5990023

Thanks a lot,
Ted

**Comment by afaissa** [comment]
Hi @tnat1031,

Understood. Thank you very much for your response!

If you don't mind, I would like to take advantage of your attention and ask another question. It's not related to package issues, so please feel free to redirect me if necessary.

I would like to plot the replicates for these two signatures for some genes of interest. Is it acceptable to present the data in this manner, or could it potentially be misleading? For instance, if I have identified a signature with high variation in a gene of interest and the replicates exhibit similarity to that signature, is it appropriate to plot this data alongside the DMSO samples on the same plate?

In the case of the LJP008_HEPG2_24H signature, I would include in the plot the corresponding DMSO samples below.

Is it permissible to proceed in this manner?

DMSO distil_ids:
LJP008_HEPG2_24H_X2_B20:A05|LJP008_HEPG2_24H_X3_B20:A05
LJP008_HEPG2_24H_X2_B20:A06|LJP008_HEPG2_24H_X3_B20:A06
LJP008_HEPG2_24H_X2_B20:B05|LJP008_HEPG2_24H_X3_B20:B05
LJP008_HEPG2_24H_X2_B20:B06|LJP008_HEPG2_24H_X3_B20:B06
LJP008_HEPG2_24H_X2_B20:F07|LJP008_HEPG2_24H_X3_B20:F07
LJP008_HEPG2_24H_X2_B20:F08|LJP008_HEPG2_24H_X3_B20:F08
LJP008_HEPG2_24H_X2_B20:F09|LJP008_HEPG2_24H_X3_B20:F09
LJP008_HEPG2_24H_X2_B20:F10|LJP008_HEPG2_24H_X3_B20:F10
LJP008_HEPG2_24H_X2_B20:F11|LJP008_HEPG2_24H_X3_B20:F11
LJP008_HEPG2_24H_X2_B20:F12|LJP008_HEPG2_24H_X3_B20:F12
LJP008_HEPG2_24H_X2_B20:J13|LJP008_HEPG2_24H_X3_B20:J13
LJP008_HEPG2_24H_X2_B20:J14|LJP008_HEPG2_24H_X3_B20:J14
LJP008_HEPG2_24H_X2_B20:J15|LJP008_HEPG2_24H_X3_B20:J15
LJP008_HEPG2_24H_X2_B20:J16|LJP008_HEPG2_24H_X3_B20:J16
LJP008_HEPG2_24H_X2_B20:J17|LJP008_HEPG2_24H_X3_B20:J17
LJP008_HEPG2_24H_X2_B20:J18|LJP008_HEPG2_24H_X3_B20:J18
LJP008_HEPG2_24H_X2_B20:N19|LJP008_HEPG2_24H_X3_B20:N19
LJP008_HEPG2_24H_X2_B20:N20|LJP008_HEPG2_24H_X3_B20:N20
LJP008_HEPG2_24H_X2_B20:N21|LJP008_HEPG2_24H_X3_B20:N21
LJP008_HEPG2_24H_X2_B20:N22|LJP008_HEPG2_24H_X3_B20:N22
LJP008_HEPG2_24H_X2_B20:N23|LJP008_HEPG2_24H_X3_B20:N23
LJP008_HEPG2_24H_X2_B20:N24|LJP008_HEPG2_24H_X3_B20:N24
LJP008_HEPG2_24H_X2_B20:P19|LJP008_HEPG2_24H_X3_B20:P19
LJP008_HEPG2_24H_X2_B20:P20|LJP008_HEPG2_24H_X3_B20:P20
LJP008_HEPG2_24H_X2_B20:P21|LJP008_HEPG2_24H_X3_B20:P21
LJP008_HEPG2_24H_X2_B20:P22|LJP008_HEPG2_24H_X3_B20:P22
LJP008_HEPG2_24H_X2_B20:P23|LJP008_HEPG2_24H_X3_B20:P23
LJP008_HEPG2_24H_X2_B20:P24|LJP008_HEPG2_24H_X3_B20:P24

**Comment by tnat1031** [comment]
Hi @afaissa,

I'm not sure I fully understand what you are trying to illustrate, but I don't believe there is any problem with plotting a subset of genes across a set of level 3, 4, or 5 samples. The clue team at the Broad may be better suited to advise on an ongoing basis. You can reach out to them via their clue.io webpage.

Thanks a lot,
Ted

**Comment by afaissa** [comment]
Thank you so much!
